In [2]:
import nltk
import spacy
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

from nltk import pos_tag
from nltk.corpus import stopwords
import re
from nltk.corpus import wordnet
import pandas as pd

# import pyterrier as pt

# if not pt.started():
#     pt.init()

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("stopwords")

pd.set_option('display.max_colwidth',200)

ModuleNotFoundError: No module named 'spacy'

In [2]:
lawyers = pd.read_csv(r"Data\lawyers.csv").rename(columns={
    "id":"lawyer_id"
}).drop(columns={"email","email_verified_at","password","remember_token","phone","affiliation_date","created_at","updated_at"})
lawyers.head()

,lawyer_id,name,address,union_branch,union_number,years_of_experience
0,1,Lawyer 1,"1 Main St, City 1",Branch 2,UN0001,1
1,2,Lawyer 2,"2 Main St, City 2",Branch 3,UN0002,4
2,3,Lawyer 3,"3 Main St, City 3",Branch 1,UN0003,12
3,4,Lawyer 4,"4 Main St, City 4",Branch 2,UN0004,13
4,5,Lawyer 5,"5 Main St, City 5",Branch 3,UN0005,15

In [3]:
rates = pd.read_csv(r"Data\rates.csv").drop(columns={"created_at","updated_at","id"})
rates.head()

   lawyer_id  user_id  rating                                review
0        127     1558       2        Very professional and helpful.
1        141     1157       5       Not satisfied with the service.
2        148     1355       3        Very professional and helpful.
3        189     1050       4       Not satisfied with the service.
4        144     1658       1  Excellent service, highly recommend!

In [ ]:
class Preprocessing_EN:
  @staticmethod
  def process(sentance):
    sentance = Preprocessing_EN.remove_punctuation(sentance)
    sentance = Preprocessing_EN.tokenizer(sentance)
    sentance = Preprocessing_EN.normalizer(sentance)
    sentance = Preprocessing_EN.remove_stopwords(sentance)
    sentance = Preprocessing_EN.remove_deplicate(sentance)
   
    sentance = Preprocessing_EN.lemmatizer2(sentance)
    # sentance = Preprocessing_EN.stemmer(sentance)
    
    return sentance

  @staticmethod
  def tokenizer(sentance):
    words = word_tokenize(sentance)
    return words

  @staticmethod
  def normalizer(sentance):
    return [word.lower() for word in sentance]

  @staticmethod
  def remove_stopwords(sentance):
    stop_words = set(stopwords.words('english'))
    sentance = [word for word in sentance if word not in stop_words]
    return sentance

  @staticmethod
  def lemmatizer1(sentance):
    lemmatize = WordNetLemmatizer()
    sentance = [lemmatize.lemmatize(word,pos="a") for word in sentance]
    return sentance
  
  
  @staticmethod
  def lemmatizer2(sentance):
    lemmatize =spacy.load("en_core_web_sm")
    sentance = [lemmatize.lemmatize(word,pos="a") for word in sentance]
    return sentance
  
  @staticmethod
  def stemmer(sentance):
    stemmer = PorterStemmer()
    sentance = [stemmer.stem(word) for word in sentance]
    return sentance

  @staticmethod
  def remove_punctuation(sentance):
    return re.sub(r'[^A-Za-z0-9\s]',' ',sentance)

  @staticmethod
  def remove_deplicate(sentance):
    return list(set(sentance))

In [9]:
text = """Artificial Intelligence (AI) is transforming industries across the globe. From healthcare to finance,
AI-powered solutions are making processes faster and more accurate. AI applications, such as natural
language processing and machine learning, are now mainstream in businesses, and their capabilities continue
to expand."""

text1 = """Rocks Making Swimming Saw Was watched see"""

Preprocessing_EN.process(text)

['continu',
 'healthcar',
 'expand',
 'fast',
 'power',
 'accur',
 'artifici',
 'machin',
 'languag',
 'mainstream',
 'make',
 'ai',
 'financ',
 'across',
 'solut',
 'capabl',
 'natur',
 'process',
 'intellig',
 'globe',
 'learn',
 'applic',
 'busi',
 'industri',
 'process',
 'transform']

In [36]:
lawyers_with_rates = lawyers.merge(rates,on="lawyer_id")

In [37]:
lawyers_with_rates['processed_text'] = lawyers_with_rates['review'].apply(Preprocessing_EN.process)
lawyers_with_rates.head()

,lawyer_id,name,address,union_branch,union_number,years_of_experience,user_id,rating,review,processed_text
0,107,Lawyer 107,"107 Main St, City 107",Branch 3,UN0107,3,1351,1,"Good, but communication could be improved.","[commun, good, could, improv]"
1,110,Lawyer 110,"110 Main St, City 110",Branch 3,UN0110,6,1358,5,Not satisfied with the service.,"[satisfi, servic]"
2,115,Lawyer 115,"115 Main St, City 115",Branch 2,UN0115,12,1515,3,"Good, but communication could be improved.","[commun, good, could, improv]"
3,121,Lawyer 121,"121 Main St, City 121",Branch 2,UN0121,13,1724,4,"Excellent service, highly recommend!","[highli, recommend, excel, servic]"
4,122,Lawyer 122,"122 Main St, City 122",Branch 3,UN0122,19,1957,4,Very professional and helpful.,"[profession, help]"

In [39]:
lawyers_with_rates['text'] = lawyers_with_rates['address'].apply(Preprocessing_EN.process)
lawyers_with_rates.head()

,lawyer_id,name,address,union_branch,union_number,years_of_experience,user_id,rating,review,processed_text,text
0,107,Lawyer 107,"107 Main St, City 107",Branch 3,UN0107,3,1351,1,"Good, but communication could be improved.","[commun, good, could, improv]","[main, citi, 107, st]"
1,110,Lawyer 110,"110 Main St, City 110",Branch 3,UN0110,6,1358,5,Not satisfied with the service.,"[satisfi, servic]","[110, main, citi, st]"
2,115,Lawyer 115,"115 Main St, City 115",Branch 2,UN0115,12,1515,3,"Good, but communication could be improved.","[commun, good, could, improv]","[main, 115, citi, st]"
3,121,Lawyer 121,"121 Main St, City 121",Branch 2,UN0121,13,1724,4,"Excellent service, highly recommend!","[highli, recommend, excel, servic]","[main, 121, citi, st]"
4,122,Lawyer 122,"122 Main St, City 122",Branch 3,UN0122,19,1957,4,Very professional and helpful.,"[profession, help]","[main, 122, citi, st]"

In [42]:
columns_to_preprocess = ['address', 'union_branch','years_of_experience','rating','review']
for col in columns_to_preprocess:
    lawyers_with_rates['text'] = lawyers_with_rates[col].apply(Preprocessing_EN.process)

TypeError: expected string or bytes-like object, got 'int'

In [43]:
lawyers_with_rates

,lawyer_id,name,address,union_branch,union_number,years_of_experience,user_id,rating,review,processed_text,text
0,107,Lawyer 107,"107 Main St, City 107",Branch 3,UN0107,3,1351,1,"Good, but communication could be improved.","[commun, good, could, improv]","[3, branch]"
1,110,Lawyer 110,"110 Main St, City 110",Branch 3,UN0110,6,1358,5,Not satisfied with the service.,"[satisfi, servic]","[3, branch]"
2,115,Lawyer 115,"115 Main St, City 115",Branch 2,UN0115,12,1515,3,"Good, but communication could be improved.","[commun, good, could, improv]","[branch, 2]"
3,121,Lawyer 121,"121 Main St, City 121",Branch 2,UN0121,13,1724,4,"Excellent service, highly recommend!","[highli, recommend, excel, servic]","[branch, 2]"
4,122,Lawyer 122,"122 Main St, City 122",Branch 3,UN0122,19,1957,4,Very professional and helpful.,"[profession, help]","[3, branch]"
5,127,Lawyer 127,"127 Main St, City 127",Branch 2,UN0127,11,1558,2,Very professional and helpful.,"[profession, help]","[branch, 2]"
6,127,Lawyer 127,"127 Main St, City 127",Branch 2,UN0127,11,1490,5,"Good, but communication could be improved.","[commun, good, could, improv]","[branch, 2]"
7,134,Lawyer 134,"134 Main St, City 134",Branch 3,UN0134,1,1280,3,"Good, but communication could be improved.","[commun, good, could, improv]","[3, branch]"
8,141,Lawyer 141,"141 Main St, City 141",Branch 1,UN0141,1,1157,5,Not satisfied with the service.,"[satisfi, servic]","[1, branch]"
9,144,Lawyer 144,"144 Main St, City 144",Branch 1,UN0144,14,1658,1,"Excellent service, highly recommend!","[highli, recommend, excel, servic]","[1, branch]"
10,146,Lawyer 146,"146 Main St, City 146",Branch 3,UN0146,14,1928,4,"Exceptional experience, would hire again!","[hire, experi, except, would]","[3, branch]"
11,148,Lawyer 148,"148 Main St, City 148",Branch 2,UN0148,5,1355,3,Very professional and helpful.,"[profession, help]","[branch, 2]"
12,164,Lawyer 164,"164 Main St, City 164",Branch 3,UN0164,19,1303,1,"Excellent service, highly recommend!","[highli, recommend, excel, servic]","[3, branch]"
13,169,Lawyer 169,"169 Main St, City 169",Branch 2,UN0169,1,1194,1,"Exceptional experience, would hire again!","[hire, experi, except, would]","[branch, 2]"
14,175,Lawyer 175,"175 Main St, City 175",Branch 2,UN0175,2,1115,2,Very professional and helpful.,"[profession, help]","[branch, 2]"
15,180,Lawyer 180,"180 Main St, City 180",Branch 1,UN0180,15,1316,4,Not satisfied with the service.,"[satisfi, servic]","[1, branch]"
16,181,Lawyer 181,"181 Main St, City 181",Branch 2,UN0181,15,1825,1,Very professional and helpful.,"[profession, help]","[branch, 2]"
17,189,Lawyer 189,"189 Main St, City 189",Branch 1,UN0189,13,1050,4,Not satisfied with the service.,"[satisfi, servic]","[1, branch]"
18,190,Lawyer 190,"190 Main St, City 190",Branch 2,UN0190,14,1736,5,Not satisfied with the service.,"[satisfi, servic]","[branch, 2]"
19,197,Lawyer 197,"197 Main St, City 197",Branch 3,UN0197,9,1255,2,"Good, but communication could be improved.","[commun, good, could, improv]","[3, branch]"